// Code generated by protoc-gen-go. DO NOT EDIT.
// source: keystorebackup.proto

package keystorebackup

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	LastRun              int64    `protobuf:"varint,1,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_b49071bc3584ad28, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetLastRun() int64 {
	if m != nil {
		return m.LastRun
	}
	return 0
}

func init() {
	proto.RegisterType((*Config)(nil), "keystorebackup.Config")
}

func init() { proto.RegisterFile("keystorebackup.proto", fileDescriptor_b49071bc3584ad28) }

var fileDescriptor_b49071bc3584ad28 = []byte{
	// 90 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc9, 0x4e, 0xad, 0x2c,
	0x2e, 0xc9, 0x2f, 0x4a, 0x4d, 0x4a, 0x4c, 0xce, 0x2e, 0x2d, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x43, 0x15, 0x55, 0x52, 0xe6, 0x62, 0x73, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0x17, 0x92,
	0xe4, 0xe2, 0xc8, 0x49, 0x2c, 0x2e, 0x89, 0x2f, 0x2a, 0xcd, 0x93, 0x60, 0x54, 0x60, 0xd4, 0x60,
	0x0e, 0x62, 0x07, 0xf1, 0x83, 0x4a, 0xf3, 0x92, 0xd8, 0xc0, 0x7a, 0x8d, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x90, 0x56, 0x74, 0x37, 0x53, 0x00, 0x00, 0x00,
}
