// Code generated by protoc-gen-go. DO NOT EDIT.
// source: keystorebackup.proto

package keystorebackup

import (
	fmt "fmt"
	proto1 "github.com/brotherlogic/keystore/proto"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AllDatums struct {
	Datums               []*Datum `protobuf:"bytes,1,rep,name=datums,proto3" json:"datums,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllDatums) Reset()         { *m = AllDatums{} }
func (m *AllDatums) String() string { return proto.CompactTextString(m) }
func (*AllDatums) ProtoMessage()    {}
func (*AllDatums) Descriptor() ([]byte, []int) {
	return fileDescriptor_b49071bc3584ad28, []int{0}
}

func (m *AllDatums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllDatums.Unmarshal(m, b)
}
func (m *AllDatums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllDatums.Marshal(b, m, deterministic)
}
func (m *AllDatums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllDatums.Merge(m, src)
}
func (m *AllDatums) XXX_Size() int {
	return xxx_messageInfo_AllDatums.Size(m)
}
func (m *AllDatums) XXX_DiscardUnknown() {
	xxx_messageInfo_AllDatums.DiscardUnknown(m)
}

var xxx_messageInfo_AllDatums proto.InternalMessageInfo

func (m *AllDatums) GetDatums() []*Datum {
	if m != nil {
		return m.Datums
	}
	return nil
}

type Datum struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *any.Any `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Datum) Reset()         { *m = Datum{} }
func (m *Datum) String() string { return proto.CompactTextString(m) }
func (*Datum) ProtoMessage()    {}
func (*Datum) Descriptor() ([]byte, []int) {
	return fileDescriptor_b49071bc3584ad28, []int{1}
}

func (m *Datum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Datum.Unmarshal(m, b)
}
func (m *Datum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Datum.Marshal(b, m, deterministic)
}
func (m *Datum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Datum.Merge(m, src)
}
func (m *Datum) XXX_Size() int {
	return xxx_messageInfo_Datum.Size(m)
}
func (m *Datum) XXX_DiscardUnknown() {
	xxx_messageInfo_Datum.DiscardUnknown(m)
}

var xxx_messageInfo_Datum proto.InternalMessageInfo

func (m *Datum) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Datum) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type Config struct {
	LastRun              int64              `protobuf:"varint,1,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	LastKeys             []*proto1.FileMeta `protobuf:"bytes,2,rep,name=last_keys,json=lastKeys,proto3" json:"last_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_b49071bc3584ad28, []int{2}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetLastRun() int64 {
	if m != nil {
		return m.LastRun
	}
	return 0
}

func (m *Config) GetLastKeys() []*proto1.FileMeta {
	if m != nil {
		return m.LastKeys
	}
	return nil
}

func init() {
	proto.RegisterType((*AllDatums)(nil), "keystorebackup.AllDatums")
	proto.RegisterType((*Datum)(nil), "keystorebackup.Datum")
	proto.RegisterType((*Config)(nil), "keystorebackup.Config")
}

func init() { proto.RegisterFile("keystorebackup.proto", fileDescriptor_b49071bc3584ad28) }

var fileDescriptor_b49071bc3584ad28 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0xcd, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0xe9, 0xc6, 0xaa, 0xcd, 0x40, 0x24, 0x4c, 0xa8, 0x3b, 0x95, 0x9e, 0x8a, 0x60, 0x02,
	0xdb, 0xcd, 0xdb, 0xf0, 0xe3, 0x22, 0x5e, 0x82, 0x77, 0x49, 0xea, 0xbb, 0xac, 0x34, 0x4b, 0x4a,
	0x3e, 0x06, 0xf9, 0xef, 0xa5, 0xa9, 0x13, 0xf5, 0x10, 0x78, 0xf3, 0xe6, 0xf7, 0x3c, 0xf9, 0xa1,
	0x55, 0x0f, 0xd1, 0x79, 0x63, 0x41, 0xf0, 0xb6, 0x0f, 0x03, 0x19, 0xac, 0xf1, 0x06, 0x5f, 0xfd,
	0xdd, 0xae, 0xb7, 0xb2, 0xf3, 0x87, 0x20, 0x48, 0x6b, 0x8e, 0x54, 0x58, 0xe3, 0x0f, 0x60, 0x95,
	0x91, 0x5d, 0x4b, 0xcf, 0x1c, 0x4d, 0x39, 0xea, 0xc0, 0x9e, 0xc0, 0x4e, 0x25, 0x6b, 0xfa, 0x2b,
	0x24, 0x8d, 0xe2, 0x5a, 0x4e, 0x94, 0x08, 0x7b, 0x3a, 0xf8, 0x38, 0x80, 0xa3, 0x5c, 0xc7, 0xf1,
	0x4c, 0x81, 0xfa, 0x01, 0x15, 0x3b, 0xa5, 0x9e, 0xb8, 0x0f, 0x47, 0x87, 0xef, 0x51, 0xfe, 0x99,
	0xa6, 0x32, 0xab, 0xe6, 0xcd, 0x72, 0x73, 0x43, 0xfe, 0x99, 0x26, 0x8e, 0x7d, 0x43, 0xf5, 0x33,
	0x5a, 0xa4, 0x05, 0xbe, 0x46, 0xf3, 0x1e, 0x62, 0x99, 0x55, 0x59, 0x53, 0xb0, 0x71, 0xc4, 0x77,
	0x68, 0x71, 0xe2, 0x2a, 0x40, 0x39, 0xab, 0xb2, 0x66, 0xb9, 0x59, 0x11, 0x69, 0x8c, 0x54, 0x40,
	0xce, 0x32, 0x64, 0xa7, 0x23, 0x9b, 0x90, 0xfa, 0x1d, 0xe5, 0x8f, 0x46, 0xef, 0x3b, 0x89, 0x6f,
	0xd1, 0xa5, 0xe2, 0xce, 0x7f, 0xd8, 0xa0, 0x53, 0xd9, 0x9c, 0x5d, 0x8c, 0x77, 0x16, 0x34, 0xa6,
	0xa8, 0x48, 0x4f, 0xa3, 0x50, 0x39, 0x4b, 0x76, 0xf8, 0xc7, 0x8e, 0xbc, 0x74, 0x0a, 0xde, 0xc0,
	0x73, 0x96, 0xf2, 0xaf, 0x10, 0x9d, 0xc8, 0xd3, 0x57, 0xdb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x3b, 0x8f, 0xe3, 0xca, 0x6d, 0x01, 0x00, 0x00,
}
